language: objective-c
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
  - bundle install
  - pod setup
  - bundle exec rake pod:install
gemfile:
  - Gemfile
script: bundle exec rake spec
env:
  global:
  - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true
